name: Build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    if: runner.os == 'Windows'
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

  build-linux:
    runs-on: ubuntu-latest
    if: runner.os == 'Linux'
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

  build-macos:
    runs-on: macos-latest
    if: runner.os == 'macOS'
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release
